In [2]:
import pandas as pd

# Create the dataset
data = {
    'ID'    : ['Eth-101', 'Eth-102', 'Eth-103', 'Eth-104', 'Eth-105'],
    'Name'  : ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse'],
    'Age'   : [25, None, 29, 33, None],
    'Salary': [55000, 48000, None, 62000, None]
}

df = pd.DataFrame(data)

# Remove rows with missing values
df_cleaned = df.dropna()

print(df_cleaned)

        ID                      Name   Age   Salary
0  Eth-101  Haileslassie Zeferu Abel  25.0  55000.0
3  Eth-104    Abraham Melisew Fireda  33.0  62000.0

In [3]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   29.0  55000.0
std     4.0   7000.0
min    25.0  48000.0
25%    27.0  51500.0
50%    29.0  55000.0
75%    31.0  58500.0
max    33.0  62000.0

In [4]:
df

        ID                      Name   Age   Salary
0  Eth-101  Haileslassie Zeferu Abel  25.0  55000.0
1  Eth-102      Worku Abenezer Girma   NaN  48000.0
2  Eth-103     Abenezer Reta Tamirat  29.0      NaN
3  Eth-104    Abraham Melisew Fireda  33.0  62000.0
4  Eth-105      Hailu Abraham Niguse   NaN      NaN

In [7]:

for column in df.columns: 
  if df[column].dtype == 'float64' or df[column].dtype == 'int64':  
     df[column].fillna(df[column].mean(), inplace=True) 
print(df)

        ID                      Name   Age   Salary
0  Eth-101  Haileslassie Zeferu Abel  25.0  55000.0
1  Eth-102      Worku Abenezer Girma  29.0  48000.0
2  Eth-103     Abenezer Reta Tamirat  29.0  55000.0
3  Eth-104    Abraham Melisew Fireda  33.0  62000.0
4  Eth-105      Hailu Abraham Niguse  29.0  55000.0

C:\Users\ISUG\AppData\Local\Temp\ipykernel_20972\3532522027.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)

In [8]:
import pandas as pd

# Create the dataset
data = {
    'ID'    : ['Eth-101', 'Eth-102', 'Eth-103', 'Eth-104', 'Eth-105'],
    'Name'  : ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse'],
    'Age'   : [25, None, 29, 33, None],
    'Salary': [55000, 48000, None, 62000, None]
}

df = pd.DataFrame(data)

# Create a column-based flag
for column in df.columns:
    if df[column].isnull().any():
        df[f'{column}_Flag'] = df[column].isna().apply(
            lambda x: 'Missing' if x else 'Not Missing'
        )

# Create a row-based flag
df['Missing_Flag'] = df.isnull().any(axis=1).apply(
    lambda x: 'Missing' if x else 'Not Missing'
)

print(df)

        ID                      Name   Age   Salary     Age_Flag  Salary_Flag  \
0  Eth-101  Haileslassie Zeferu Abel  25.0  55000.0  Not Missing  Not Missing
1  Eth-102      Worku Abenezer Girma   NaN  48000.0      Missing  Not Missing
2  Eth-103     Abenezer Reta Tamirat  29.0      NaN  Not Missing      Missing
3  Eth-104    Abraham Melisew Fireda  33.0  62000.0  Not Missing  Not Missing
4  Eth-105      Hailu Abraham Niguse   NaN      NaN      Missing      Missing

  Missing_Flag
0  Not Missing
1      Missing
2      Missing
3  Not Missing
4      Missing

In [9]:
import pandas as pd

# Sample dataset
data = {
    'ID'    : ['Eth-101', 'Eth-102', 'Eth-103', 'Eth-104', 'Eth-105', 'Eth-102', 'Eth-104', 'Eth-106'],
    'Name'  : ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse', 'Worku Abenezer Girma', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse'],
    'Age'   : [25, 29, 29, 33, 29, 29, 33, 29],
    'Salary': [55000, 48000, 55000, 62000, 55000, 48000, 62000, 55000],
    'City'  : ['Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Adama', 'Addis Ababa']
}

# Original Dataset
df = pd.DataFrame(data)
print("Original Dataset")
print(df, '\n')

Original Dataset
        ID                      Name  Age  Salary         City
0  Eth-101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth-102      Worku Abenezer Girma   29   48000        Adama
2  Eth-103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth-104    Abraham Melisew Fireda   33   62000        Adama
4  Eth-105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth-102      Worku Abenezer Girma   29   48000        Adama
6  Eth-104    Abraham Melisew Fireda   33   62000        Adama
7  Eth-106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [10]:
# Exact Match - based on all columns 
df_cleaned = df.drop_duplicates() 
print("Duplicates Removed - Exact Match") 
print(df_cleaned, '\n')

Duplicates Removed - Exact Match
        ID                      Name  Age  Salary         City
0  Eth-101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth-102      Worku Abenezer Girma   29   48000        Adama
2  Eth-103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth-104    Abraham Melisew Fireda   33   62000        Adama
4  Eth-105      Hailu Abraham Niguse   29   55000  Addis Ababa
7  Eth-106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [11]:
df_cleaned_id = df.drop_duplicates(subset=['ID']) 
print("Duplicates Removed - Partial Match based on ID") 
print(df_cleaned_id, '\n')

Duplicates Removed - Partial Match based on ID
        ID                      Name  Age  Salary         City
0  Eth-101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth-102      Worku Abenezer Girma   29   48000        Adama
2  Eth-103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth-104    Abraham Melisew Fireda   33   62000        Adama
4  Eth-105      Hailu Abraham Niguse   29   55000  Addis Ababa
7  Eth-106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [12]:
df_cleaned_id = df.drop_duplicates(subset=['Age']) 
print("Duplicates Removed - Partial Match based on ID") 
print(df_cleaned_id, '\n')

Duplicates Removed - Partial Match based on ID
        ID                      Name  Age  Salary         City
0  Eth-101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth-102      Worku Abenezer Girma   29   48000        Adama
3  Eth-104    Abraham Melisew Fireda   33   62000        Adama